<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptableRepository extends EntityRepository
{
    
    public function findByMdpAndLogin($login, $mdp){
        
        $queryBuilder = $this->createQueryBuilder('c')->where('c.login = :login')->andWhere('c.mdp = :mdp')->setParameter('login', $login)->setParameter('mdp', $mdp);
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
