<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptableRepository extends EntityRepository
{
    
    public function findByMdpAndLogin($login, $mdp){
        
        $queryBuilder = $this->createQueryBuilder('c')->where('c.login = :login')->andWhere('c.mdp = :mdp')->setParameter('login', $login)->setParameter('mdp', $mdp);
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
    
    public function updateConnecteToTrue($login){
        
        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('rvmgGSBBundle:Comptable', 'c')
            ->set('c.connecte', 1)
            ->where('c.login = :login')
            ->setParameter('login' ,$login);
         
        $qB->getQuery()->execute();
    }
    
    public function updateConnecteToFalse($login){
        
        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('rvmgGSBBundle:Comptable', 'c')
            ->set('c.connecte', 0)
            ->where('c.login = :login')
            ->setParameter('login' ,$login);
         
        $qB->getQuery()->execute();
    }
}
