<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichefraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends EntityRepository
{
    
    public function findOneByCurrentMonth($visiteur){
        
        $queryBuidler = $this->createQueryBuilder('f');
        $queryBuidler->where('f.idvisiteur = :visiteur')->where('f.mois = month(now())')
                ->setParameter(':visiteur', $visiteur);
        return $queryBuilder->getQuery()->getOneOrNullResult();
        
    }
    
    public function findOneByMonthAndVisitor($visitor, $month){
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->where('f.idvisiteur = :visiteur')->setParameter(':visiteur', $visitor)
                ->andWhere('f.mois = :mois')->setParameter(':mois',$month);
                //->where('year(f.mois) = :annee')->setParameter(':annee', $month->format('y'));
        //TODO modifier la requête pour rechercher une fiche d'une meilleure manière
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
    
}
