<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichefraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends EntityRepository
{
    
    public function findOneByCurrentMonth($visiteur){
        
        $queryBuidler = $this->createQueryBuilder('f');
        $queryBuidler->where('f.idvisiteur = :visiteur')->where('f.mois = month(now())')
                ->setParameter(':visiteur', $visiteur);
        return $queryBuilder->getQuery()->getOneOrNullResult();
        
    }
    
}
