<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LignefraisforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraisforfaitRepository extends EntityRepository
{
    public function removeAll(){
        $query = $this->createQueryBuilder('l')
                ->delete()->getQuery()->execute();
        
        return $query;
    }
}
