<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LignefraishorsforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraishorsforfaitRepository extends EntityRepository
{
    
    public function findOneByIdAndIdFicheFrais($fichefrais, $idligne){
        $queryBuilder = $this->createQueryBuilder('l');
        $queryBuilder->where('l.idfichefrais = :fichefrais')->setParameter(':fichefrais', $fichefrais)
                ->andWhere('l.idlignefraishorsforfait = :idligne')->setParameter(':idligne',$idligne);
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
    
}
