<?php

namespace rvmg\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends EntityRepository
{
    
    public function findByMdpAndLogin($login, $mdp){
        
        $queryBuilder = $this->createQueryBuilder('v');
        $queryBuilder->where('v.login = :login')->setParameter('login',$login)->andWhere('v.mdp = :mdp')->setParameter('mdp',$mdp);
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
