parameters:
    pdo.class: PDO
    pdo.attr_errmode: 3
    pdo.erromode_exception: 2
    pdo.options:
        %pdo.attr_errmode%: %pdo.erromode_exception%
    dbFrais.dsn: mysql:host=localhost;dbname=gsbFrais
    dbFrais.username: appli
    dbFrais.password: azerty