rvmg_gsb_homepage:
    path:     /
    defaults: { _controller: rvmgGSBBundle:Accueil:connexionAccueil }

rvmg_gsb_connexionErreur:
    path:   /connexionErreur
    defaults: { _controller: rvmgGSBBundle:Accueil:connexionAccueil }
    
rvmg_gsb_deconnexion:
    path:   /deconnexion
    defaults: { _controller: rvmgGSBBundle:Accueil:deconnexion }
    
rvmg_gsb_renseigner_forfait:
    path:     /renseigner/forfait
    defaults: { _controller: rvmgGSBBundle:Visiteur:renseignerForfait }
    
rvmg_gsb_annuler_forfait:
    path:   /annuler/forfait/{id}
    defaults: { _controller: rvmgGSBBundle:Visiteur:annulerForfait }
    
rvmg_gsb_supprimer_forfait:
    path:   /supprimer/forfait
    defaults: { _controller: rvmgGSBBundle:Visiteur:supprimerForfait }
    
rvmg_gsb_renseigner_horsforfait:
    path:     /renseigner/horsforfait
    defaults: { _controller: rvmgGSBBundle:Visiteur:renseignerHorsForfait }

rvmg_gsb_consulter:
    path:     /consulter
    defaults: { _controller: rvmgGSBBundle:Visiteur:consulter }
    
rvmg_gsb_validate:
    path:     /valider/{fichefrais}
    defaults: { _controller: rvmgGSBBundle:Comptable:validate }
    
rvmg_gsb_choose_month_visitor:
    path:     /choisir/
    defaults: { _controller: rvmgGSBBundle:Comptable:chooseMonthAndVisitor }
    
rvmg_gsb_refuse_horsforfait:
    path:     /refuser/{fichefrais}/{ligne}
    defaults: { _controller: rvmgGSBBundle:Comptable:refuserHorsForfait }

rvmg_gsb_choose_fiche_frais:
    path:     /choisir/fichefrais
    defaults: { _controller: rvmgGSBBundle:Comptable:chooseFicheFrais }
    
rvmg_gsb_follow:
    path:     /suivre/{fichefrais}
    defaults: { _controller: rvmgGSBBundle:Comptable:follow }