rvmg_gsb_homepage:
    path:     /
    defaults: { _controller: rvmgGSBBundle:Accueil:connexionAccueil }

rvmg_gsb_connexionErreur:
    path:   /connexionErreur
    defaults: { _controller: rvmgGSBBundle:Accueil:connexionAccueil }