rvmg_gsb_homepage:
    path:     /
    defaults: { _controller: rvmgGSBBundle:Accueil:connexionAccueil }

rvmg_gsb_connexionErreur:
    path:   /connexionErreur
    defaults: { _controller: rvmgGSBBundle:Accueil:connexionAccueil }
    
rvmg_gsb_deconnexion:
    path:   /deconnexion
    defaults: { _controller: rvmgGSBBundle:Accueil:deconnexion }
    
rvmg_gsb_renseigner:
    path:     /renseigner/{type}
    defaults: { _controller: rvmgGSBBundle:Visiteur:renseigner }
    
rvmg_gsb_valider:
    path:     /valider/
    defaults: { _controller: rvmgGSBBundle:Comptable:valider }
    
rvmg_gsb_suivre:
    path:     /suivre/
    defaults: { _controller: rvmgGSBBundle:Comptable:suivre }
    
rvmg_gsb_choose_month_visitor:
    path:     /choisir/
    defaults: { _controller: rvmgGSBBundle:Comptable:valider }
    
rvmg_gsb_refuse_horsforfait:
    path:     /refuser/{idLigne}
    defaults: { _controller: rvmgGSBBundle:Comptable:refuserHorsForfait }